project:
  type: website
  resources:
    - cv.pdf

website:
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Courses.qmd
        text: Coursework 
      - href: Projects.qmd
        text: Projects

  page-footer:
    right: "&copy;Â© 2025 Keivan Bolouri"
    

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual
